version: '3.8'  # Diperbarui ke versi terbaru
services:
  my-sql-server:
    container_name: my-sql-server
    image: mysql:8.0 #gimats/java-api-jwt:mysql #mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_DATABASE=store_database
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=admin123
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:  # Ditambahkan untuk memastikan MySQL siap
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s
    networks:
      - app-network  # Ditambahkan untuk jaringan eksplisit

  java-crud-app:
    container_name: java_api
    image: gimats/java-api-jwt:v1.0.3
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://my-sql-server:3306/store_database?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true  # Diperbarui untuk Spring Boot
      - SPRING_DATASOURCE_USERNAME=dbuser
      - SPRING_DATASOURCE_PASSWORD=admin123
    depends_on:
      my-sql-server:
        condition: service_healthy  # Menunggu MySQL sehat
    networks:
      - app-network  # Ditambahkan untuk jaringan eksplisit

volumes:
  mysql_data:

networks:
  app-network:  # Jaringan eksplisit untuk isolasi
    driver: bridge